# Configuration file for Verdaccio

# Storage
storage: /verdaccio/storage

# Auth
auth:
    htpasswd:
        file: /verdaccio/conf/htpasswd

# Uplinks
uplinks:
    npmjs:
        url: https://registry.npmjs.org/

# Packages
packages:
    "@*/*":
        access: $authenticated
        publish: $authenticated
        delete: $authenticated
        proxy: npmjs
    "**":
        access: $authenticated
        publish: $authenticated
        delete: $none
        proxy: npmjs

# Logs
logs:
    - { type: stdout, format: pretty, level: http }
