# Bind to all interfaces to allow external access
listen: 0.0.0.0:80

# Storage
storage: /verdaccio/storage

# Auth
auth:
    htpasswd:
        file: /verdaccio/conf/htpasswd
        # Switch to bcrypt (instead of crypt) for password encryption
        algorithm: bcrypt

# Uplinks
uplinks:
    npmjs:
        url: https://registry.npmjs.org/

# Packages
packages:
    "@*/*":
        access: $authenticated
        publish: $authenticated
        delete: $authenticated
        proxy: npmjs
    "**":
        access: $authenticated
        publish: $authenticated
        delete: $none
        proxy: npmjs

# Log (Update deprecated 'logs' to 'log')
log:
    type: stdout
    format: pretty
    level: http
