version: "3"
services:
    verdaccio:
        image: verdaccio/verdaccio:latest
        container_name: verdaccio
        volumes:
            - ./storage:/verdaccio/storage
            - ./conf:/verdaccio/conf
        networks:
            - verdaccio_net

networks:
    verdaccio_net:
        driver: bridge
